### PR TITLE
Push up to 345268951

### PR DESCRIPTION
**Pull request by yilei**

### CODE REVIEW

**Comment by bhack** [comment]
Is this still valid after this PR?

https://github.com/abseil/abseil-py/blob/cd53de736e73246d118848d2ac1e927f3c2cbe95/absl/BUILD#L3

**Comment by yilei** [comment]
@bhack you are right, these should also be removed. thanks!

**Comment by bhack** [comment]
Do we need to export It from a `BUILD` file in the root directory?

**Comment by yilei** [comment]
Are you having issues without it? I think we could provide one if there is need.

**Comment by bhack** [comment]
Currently on an upgrade from `0.10.0` to `0.14.0` it is failing on one rule on TF. 
If you see the CI log on win it Is looking for `LICENSE` in `absl` subdir but the file is missing:

https://github.com/tensorflow/tensorflow/pull/52173

**Comment by yilei** [comment]
Ah got it. I'll add the top-level BUILD file and export the LICENSE file. Then

https://github.com/tensorflow/tensorflow/blob/5d070584cb31d4e50bd5d361621c3ff414acdb6e/tensorflow/tools/pip_package/BUILD#L263-L267

Should become `"@absl_py//:LICENSE",`

**Comment by bhack** [comment]
Thanks

**Pull request merged**
