### PR TITLE
define multi-fields with iterable types

### PR DESCRIPTION
**Pull request by siavash-khodadadeh**
We can define multi-fields with any kind of iterable instead of just lists. The created flags are always converted to list for consistency.

### CODE REVIEW

**Comment by rickeylev** [comment]
Sorry for the long delay!

I think this is fine. I need to copy this to our internal repo, test it, and then commit and push it back, though, which will take several days.

**Comment by siavash-khodadadeh** [comment]
@rickeylev 
That is great. Thank you.

**Comment by siavash-khodadadeh** [comment]
Conflicts are resolved.

**Comment by rickeylev** [comment]
Thanks. I've imported this internally and am running our global test suite.

**Pull request closed without merging**
