### PR TITLE
fix for Python 3.8 BC breaking logging API change

### PR DESCRIPTION
**Pull request by inoryy**
Relevant issues:
* https://github.com/tensorflow/tensorflow/issues/35027
* https://github.com/deepmind/pysc2/issues/286

### CODE REVIEW

**Comment by yilei** [comment]
Thanks for the PR! Will merge once confirming all tests pass.

**Comment by svenstaro** [comment]
Can you make a release with this since with the current version, tensorflow 2.1.0rc1 is broken?

**Comment by yilei** [comment]
Yes I'll do it tomorrow Tuesday (when releases usually happen)

**Comment by yilei** [comment]
https://pypi.org/project/absl-py/0.9.0/ released.

**Pull request merged**
